version: 2.1

orbs:
  tools: replikativ/clj-tools@0

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/build:
          jarname: "datahike-backend-template"
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/deploy-snapshot:
          jarname: "datahike-backend-template"
          context:
            - clojars-deploy
            - dockerhub-deploy
          filters:
            branches:
              only: development
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/integrationtest
            - tools/build
      - tools/deploy-release:
          jarname: "datahike-backend-template"
          context:
            - clojars-deploy
            - dockerhub-deploy
          filters:
            branches:
              only: master
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/integrationtest
            - tools/build
