version: 2.1

executors:
  leiningen:
    docker:
      - image: circleci/clojure:openjdk-8-lein
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    working_directory: /home/circleci/datahike

jobs:
  setup:
    executor: leiningen
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          keys:
            - deps-{{ checksum "project.clj" }}
            - deps-
      - run: lein deps
      - save_cache:
          key: deps-{{ checksum "project.clj" }}
          paths:
            - /home/circleci/.m2
            - /home/circleci/.lein

  integrationtest:
    executor: leiningen
    docker:
      - image: circleci/clojure:openjdk-8-lein
      - image: circleci/dynamodb:latest
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run Integrationtests
          command: ./bin/run-integrationtest
          no_output_timeout: 5m

  deploy:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          command: lein deploy clojars

workflows:
  build_test_and_release:
    jobs:
      - setup
      - unittest:
          requires:
            - setup
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - setup
            - integrationtest
